-- -----------------------------------------------------
-- Table banca.TADOMICILIO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS banca.TADOMICILIO (
  FINUMERO INT NOT NULL AUTO_INCREMENT,
  FCCALLE VARCHAR(150) NOT NULL,
  FCCOLONIA VARCHAR(100) NOT NULL,
  FCESTADO VARCHAR(50) NOT NULL,
  FICODIGOPOSTAL INT NOT NULL,
  FIESTADODOMICILIO INT NOT NULL,
  PRIMARY KEY (FINUMERO))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table banca.TABANCO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS banca.TABANCO (
  FINUMERO INT NOT NULL AUTO_INCREMENT,
  FCNOMBRE VARCHAR(150) NOT NULL,
  RFC VARCHAR(15) NOT NULL,
  TELEFONO VARCHAR(15) NOT NULL,
  FIESTADOBANCO INT NOT NULL,
  FIDOMICILIO INT NOT NULL,
  PRIMARY KEY (FINUMERO)
)
ENGINE = InnoDB;

ALTER TABLE banca.TABANCO ADD CONSTRAINT FOREIGN KEY (FIDOMICILIO) REFERENCES banca.TADOMICILIO (FINUMERO);


-- -----------------------------------------------------
-- Table banca.TACLIENTE
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS banca.TACLIENTE (
  FINUMERO INT NOT NULL AUTO_INCREMENT,
  FCNOMBRE VARCHAR(150) NOT NULL,
  FDFECHANACIMIENTO DATETIME NOT NULL,
  FCRFC VARCHAR(15) NOT NULL,
  FIDOMICILIO INT NOT NULL,
  FIESTADOCLIENTE INT NOT NULL,
  FIBANCO INT NOT NULL,
  PRIMARY KEY (FINUMERO)
)
ENGINE = InnoDB;

ALTER TABLE banca.TACLIENTE ADD CONSTRAINT FOREIGN KEY (FIDOMICILIO) REFERENCES banca.TADOMICILIO (FINUMERO);
ALTER TABLE banca.TACLIENTE ADD CONSTRAINT FOREIGN KEY (FIBANCO) REFERENCES banca.TABANCO (FINUMERO);

-- -----------------------------------------------------
-- Table banca.TACUENTA
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS banca.TACUENTA (
  FINUMERO INT NOT NULL AUTO_INCREMENT,
  FDFECHAAPERTURA DATETIME NOT NULL,
  FDSALDO DECIMAL(13,2) NOT NULL,
  FDFECHACANCELACION DATETIME NOT NULL,
  FDTASADEINTERESANUAL DECIMAL(13,2) NULL,
  FDCOSTOMANEJOMENSUAL DECIMAL(13,2) NULL,
  FITIPODECUENTA INT NOT NULL,
  FIESTADOCUENTA INT NOT NULL,
  FICLIENTE INT NOT NULL,
  PRIMARY KEY (FINUMERO)
)
ENGINE = InnoDB;

ALTER TABLE banca.TACUENTA ADD CONSTRAINT FOREIGN KEY (FICLIENTE) REFERENCES banca.TACLIENTE (FINUMERO);


-- -----------------------------------------------------
-- Table banca.TAPROBLEMACUENTA
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS banca.TAPROBLEMACUENTA (
  FINUMERO INT NOT NULL AUTO_INCREMENT,
  FCDESCRIPCION VARCHAR(250) NOT NULL,
  FDFECHAPROBLEMA DATETIME NOT NULL,
  FIESTADOPROBLEMA INT NOT NULL,
  FICUENTA INT NOT NULL,
  PRIMARY KEY (FINUMERO)
)
ENGINE = InnoDB;

ALTER TABLE banca.TAPROBLEMACUENTA ADD CONSTRAINT FOREIGN KEY (FICUENTA) REFERENCES banca.TACUENTA (FINUMERO);
